# Generated by Django 4.1.7 on 2023-03-09 11:53

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("january", "January"),
                            ("february", "February"),
                            ("march", "March"),
                            ("april", "April"),
                            ("may", "May"),
                            ("june", "June"),
                            ("july", "July"),
                            ("august", "August"),
                            ("september", "September"),
                            ("october", "October"),
                            ("november", "November"),
                            ("december", "December"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(2200),
                            django.core.validators.MinValueValidator(1900),
                        ]
                    ),
                ),
            ],
        ),
    ]
