# Generated by Django 4.1.7 on 2023-03-08 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=127)),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "type",
                    models.CharField(
                        choices=[("entry", "Entry"), ("output", "Output")],
                        default="entry",
                        max_length=12,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="not selected",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="finances",
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
