# Generated by Django 4.1.7 on 2023-03-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("finances", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finance",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finances",
                to="categories.category",
            ),
        ),
    ]
